### ISSUE TITLE
Names of resources created by the operator

### ISSUE THREAD

**Issue by fraborg** [netgroup-polito/CrownLabs#139]
The name of the resources is based on the LabTemplate name, there are no checks of possible troublesome names (for example max length, accepted characters...) and also there are some mismatches in the resources names (for example the LabInstance has a random number different from the one of all other resources)

**Comment by giorio94** [comment]
This problem has partially been addressed in #313. The name of the resources is now based on the one of the labinstance (instead of the labtemplate) with the addition of a random number. Yet, leaving open since the checks regarding troublesome names are still missing (at the moment, there is only a workaround in case a `.` is present).
